services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open_webui:/app/backend/data
    depends_on:
      - ollama
      - searxng
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: 5
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
      GROQ_API_BASE_URL: ${GROQ_API_BASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      USE_OLLAMA_DOCKER: true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - adguard_network

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - 8080:8080
    volumes:
      - searxng:/etc/searxng:rw
    environment:
      SEARXNG_HOSTNAME: localhost:8080/
      SEARXNG_UWSGI_WORKERS: 3
      SEARXNG_UWSGI_THREADS: 3
    restart: unless-stopped
    cap_drop:
      - ALL # Remove this entry only for the first run and reintroduce it after the first run
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - adguard_network

volumes:
  ollama:
    external:
      true
  open_webui:
    external:
      true
  searxng:
    external:
      true

networks:
  adguard_network:
    external: true
