services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - plex-server-data:/config
      - /media/rsukumar/Ext_Disk_1/Videos:/media/Disk1
      # - /media/rsukumar/Ext_Disk_2/Videos:/media/Disk2
      # - /media/rsukumar/Ext_Disk_3/Videos:/media/Disk3
      # - /media/rsukumar/Ext_Disk_4/Videos:/media/Disk4
      # - /media/rsukumar/Ext_Disk_5/Videos:/media/Disk5
      # - /media/rsukumar/Ext_Disk_6/Videos:/media/Disk6
      # - /media/rsukumar/Ext_Disk_7/Videos:/media/Disk7
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - adguard_network

volumes:
  plex-server-data:

networks:
  adguard_network:
    external: true
