services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - jellyfin-config:/config
      # - /media/rsukumar/disk4s1/Movies:/movies
      - /media/rsukumar/Ext_Disk_5/Videos:/media/Disk5
    restart: unless-stopped

volumes:
  jellyfin-config:

