services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    entrypoint: caddy run --config /etc/caddy/Caddyfile
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - adguard-network

volumes:
  caddy_data:
  caddy_config:

networks:
  adguard-network:
    external: true