services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - adguard-network
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy_data:
  caddy_config:

networks:
  adguard-network:
    external: true